language: java
jdk:
- oraclejdk8
script:
- "./gradlew check publishGhPages"
sudo: false
env:
  global:
  - GH_REF: github.com/sethrylan/bayesian.git
  - secure: rhHL9M3JBKoKXEYEl+ADYbeoEJdRqqaEnWdrqD5G5+POBfSAoXrg66+xJZSmtYt7mxGQ2/RruDVvp4GHzi2LBk2YJYP996jQi9CsXHvMabF7nC1rhHOS9tkfLsXuWewyD0IZqzOWWTTCpfRSKSJwUEmpg3Ky6+k9WniOkv7CZ5XKJsAJsFMWW6h0opXPlM8NNCDARWnE1Nmey78XY9FqI7tRTHJLQ1o8WlK9WqJovv914+CAbv1B0oOQ8ngWk+UI7rVukXLK2lC99zwFs+v4w207w2j2hvgLL0aLow8nNgZavw3X/ja0WsTcDhpaSApLi06vhZf1QuRIw6RHZetltBneZKyvbQb2PMn58Sa9t8HPwYAoJ+4ZB09csoAp15xQTPjjL5eqh4Txzpg9ewub0c2o99/QGHjF3b98MAWMni8aiyTCF2T1ub1jTCOSFZPW+cKvuPGdtL9PQdBCLBAEcSzZekATW4Z2Y0sLCEYhsW+DLc/9//TUX5YRLBSh4UZqtx6rBDOCUmZmA/9XjygHITJDcSxVx5p/waylwT/ph6V9hnGH8LjZzf85AEcra6W5g+3guCspnGYVDl4ejnh6QPyo/822vhNjDAnvtC5fnMt+cH5Kcsg04WAGwxwdE0fVFnjfDJoyiZPg36HefOnJhIXZQtHLSJau7uiLQFtgMPo=
branches:
  only:
  - master
notifications:
  email:
  - seth.rylan@gmail.com
