---
language: java
jdk:
  - oraclejdk8
install: /bin/true
script:
  - git push "https://${GH_TOKEN}@${GH_REF}" `git subtree split --prefix client master`:gh-pages --force > /dev/null 2>&1
sudo: false
env:
  global:
  - GH_REF: github.com/sethrylan/bayesian.git
  - secure: "KQD/8U+WHOUFMkRj+OrFx7Xkm8o8wrgSVaAz4cemigGa/++0qqkr2mYlWGl2lK1cjdo20DBqMx98OTcSW2Mr59XAd0gU7WlCxdwaZneSswvhaC4qe56XEgHicdN3q90AQM3VYAa0plza614DQ2GV7Bt20edwZrOZx52PoRBg1KoSgAR9dszu8UKw6TClsDl2/uC2kuX0alqyayBwTNA9KhqrH7GFaJf+GhH/0tJyDf8rk/9VkREUu+bV1BwLrFGorC4z+quI7YSIxpTLoMwvO/4YPKXKmkXjGWaKDRCUo9QQmngdQp5b1UyiuyxF0+vZ/aW3XK0nWcJ00tFfmUBHKVTCU3rckgWk9UQoT5Lx226+8xTLkwO6CIAKTjOJ5e66Ol5elwD/G7E4NpsSBxkNt3gLF/VGSIqD8RAxxbhBKIeDvRrZ1ANdvminK3xjz+/vDch3sMvJBUHhypQxXZJjKHawmeMqPVTDxbDzZODX0ggBH1vq9G9yPzssMU5KTUoK3oVSZru+RKW3tyh5Ys4GkOko7J2gYr3Wk4tA+hB0tuA7iImC6kUlw9cofXDjgfheldUVDgoSSwfCYtAnXOX43MCLfJSEncqG5eHabzGLcbc1LUbtV8CKaL/WnpMwrGXu8w1NlWP5S1UFeqTszas55o25ZBtICPgeVg2wJw9iUGU="
branches:
  only:
  - master
notifications:
  email:
  - seth.rylan@gmail.com
