url:         http://sethrylan.org/bayesian
baseurl:     /
title:       An Educated Guess
port:        4000
safe:        false  # defaults to true on gh-pages (see https://help.github.com/articles/using-jekyll-with-pages/)
lsi:         true
highlighter: rouge
permalink:   date
markdown:    kramdown
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex
  png_url:   /images/latex
googleanalytics:
  account:   UA-33138107-1
author:
  name:      Seth Rylan Gainey
  email:     seth@sethrylan.org
  obfuscatedemail: mailto:seth{at}sethrylan{dot}org
navigation:
  - text:    Home
    url:     /index.html
