name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_svelte:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        npm install
        npm run build
