name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: QuestionsV2
        runtime: go113
        credentials: ${{ secrets.gcp_cloud_function_creds }}
        max_instances: 2
    - id: test-cloud-function
      run: curl "${{ steps.deploy.outputs.url }}"
